### ISSUE TITLE
Question about bin2cell filtering parameters in spatial transcriptomics

### ISSUE THREAD

**Issue by Jangwon-Oh** [Teichlab/bin2cell#10]
Thank you for creating such an amazing analysis tool. I'm truly grateful for it.
In bin2cell, Human colorectal cancer [bin2cell] and [downstream analysis]
for the previous sample, min cell and min gene counts were set to 3 and 1, while for the 8 x 8 micrometer spot, min cell was set to 3 and min gene counts to cases below 100. Is there a reason for this? Some cells are being lost due to this, and I'm curious if there's a standard for gene counts in spatial data

![image](https://github.com/user-attachments/assets/c5b7d924-161e-4fa3-b541-a0d259c22921)

![image](https://github.com/user-attachments/assets/d95250da-543d-441f-86b9-6c03eb71fb45)

![다운로드 (97)](https://github.com/user-attachments/assets/948a5f13-60ac-4a2d-9f71-e96b3c90d680)

Could you please provide insights on the reasoning behind these different filtering criteria and how they might affect the analysis of spatial transcriptomics data

**Comment by nadavyayon** [comment]
Hi, thanks for this question, 

For the first you are referring to the 2um object, as is mentioned in the comment in the code, we are removing null spots that don't have any genes and genes that are basically non detected in the entire tissue.The reason for this here, like any filtering, is to remove noise, focus on relevant information and also for better efficiently. in any case these cutoffs are really minimal here so you would probably not gain from removing them. 

For the other filtering of 100:
First of all there is no standard for spatial gene expression. 
Second, bin2cell is meant for single cell spatial analysis as opposed to just exploring the gene expression profiles across the tissue (which is also fine) and we wanted to compare it to "what you would do with the 8um bin if you didn't have b2c" and still wanted to get close to a single cell object in terms of numbers and cell distributions. 
We found that in this case the cutoff yielded something reasonable. In fact, in the next version of the b2c paper we also tried a higher cutoff of 8um and we will hopefully publish this comparison soon so it will be more clear. lowering this cutoff would just bring you back to tissue analysis and not cells.  

Saying that, we took the same cutoff to the b2c mostly for comparing to the 8um. This could be lower for b2c and you might want to do that if it's 100% critical to get all the cells 

Hope this answered your original intent in this question as I got a bit carried away here :) 

N

**Comment by nadavyayon** [comment]
nice image btw

**Comment by Jangwon-Oh** [comment]
Thank you for your kind and detailed explanation.
We are currently comparing VISIUM HD and Xenium 5K, and I thought we should take advantage of the high resolution when analyzing tissue images. However, since the gene capture and UMI counts are not yet at a level we're satisfied with in VISIUM HD, I was curious about how you set the criteria for cut-offs. Thank you!

**Comment by ktpolanski** [comment]
`In[15]` of the downstream analysis notebook has the bin2cell output filtered with a 100 gene minimum as well
