### ISSUE TITLE
Add stardist probability outputs on gex segmentation

### ISSUE THREAD

**Issue by ConstensouxAlexis** [Teichlab/bin2cell#12]
Hello,
I work with bin2cell version '0.3.0'.
I performed the nucleus segmentation with stardist on the gene expression image:
![image](https://github.com/user-attachments/assets/479d2c98-322b-4ca0-b8da-5d7ec1171b99)

But the probability threshold I used is too low for my data, and too many cells are segmented:
![image](https://github.com/user-attachments/assets/d347d55c-61b8-40d3-9cfe-d4ff0366d425)

I would like to put a higher probability threshold, but the segmentation probabilities are not stored in the anndata after running stardist. Thus, if I want to do some postprocessing on the gene expression segmentation, I must run stardist on my own, without using the bin2cell package; it could be very useful that bin2cell stores the outputted probabilities in the anndata !

Thank you very much

**Comment by ktpolanski** [comment]
1. You're displaying the segmentation results of the gene expression total. Take a look at how `n_counts_adjusted` looks in the area.
2. Being able to store StarDist probabilities per object would be great, but I haven't found a way to get that output from `predict_instances_big()`. If there is a way, let me know how and I'll happily work it in.

**Comment by ConstensouxAlexis** [comment]
Thank you for your answer !
