### ISSUE TITLE
Multiple segmentations per nucleus after `b2c.stardist()`

### ISSUE THREAD

**Issue by Nick-Eagles** [Teichlab/bin2cell#14]
Hello,

I'm following along [the notebook](https://nbviewer.org/github/Teichlab/bin2cell/blob/main/notebooks/demo.ipynb) with human brain data. After segmentation with `b2c.stardist()`, a given actual nucleus tends to be segmented with many small circles, rather than one single nuclear segmentation. I've attached a picture of a small region with this behavior. From your notebook, I inferred that playing around with `prob_thresh` and `nms_thresh` might solve the issue. I used default `prob_thresh`, and separately lowered `nms_thres` to 0.1, neither of which seemed to noticeably affect the segmentation behavior. Have you seen this behavior before, or do you have recommendations of code to try?

<img width="415" alt="Screenshot 2024-09-24 at 1 15 55 PM" src="https://github.com/user-attachments/assets/763e7678-436c-4aed-96ea-33f5ccce6ff9">

Best,
-Nick

**Comment by ktpolanski** [comment]
I'm assuming you're referring to H&E segmentation.

What is the image I'm looking at? Is this a zoom-in on part of `sc.pl.spatial()` after importing the labels into the object?

**Comment by Nick-Eagles** [comment]
Yes, this is H&E segmentation with a close zoom on labels plotted with `sc.pl.spatial()`

**Comment by ktpolanski** [comment]
Then the circles you're seeing are the 2um bins. That's why there are multiple dots per nucleus.

Try shrinking your crop (in the demo notebook, it's controlled via the array coordinate ranges in `In[7]`) so that you have fewer objects in the plot and they should colour nicely.

**Comment by Nick-Eagles** [comment]
Ah that's a silly mistake-- the nuclei in the example notebook are large enough that I didn't notice they were composed of individual bins, and I misunderstood what the plot was showing. Thanks so much for your prompt responses!

**Comment by lcolladotor** [comment]
Thanks again for your prompt responses @ktpolanski & team. Nick just presented a journal club about your software to my team today: https://youtu.be/ZY9N4spEZ_Q.

(FYI I posted about it on X/Twitter, Bluesky, and LinkedIn)

Best,
Leo

**Comment by nadavyayon** [comment]
Thank you veru much!
