### ISSUE TITLE
Where is Celltypist dataset

### ISSUE THREAD

**Issue by mHagiw** [Teichlab/bin2cell#15]
Thank you for creating the beautiful tool !!

I have a small question about the Celltypist part of the CRC tutorial.

Where can I find the file used in the following part of the tutorial? 
Do I need to create it myself?

/nfs/team205/rb29/VisiumHD_intestine/Src/celltypist_models/model_from_megaGut_colon_CRC_level3.pkl

**Comment by ktpolanski** [comment]
The model is the product of a paper that has encountered some surprise publication delays, and the file should be available soon. For now, we've regenerated the notebook with just the public model and updated the link.
