### ISSUE TITLE
H&E image requirements

### ISSUE THREAD

**Issue by liyiwang0725** [Teichlab/bin2cell#17]
Hi,
Thank you for sharing this amazing package. I meet some problems when I performed the `b2c.scaled_he_image` step. The error as follows:
`>>> b2c.scaled_he_image(adata, mpp=0.5, save_path="stardist/he.tiff")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.12/site-packages/bin2cell/bin2cell.py", line 697, in scaled_he_image
    img = cv2.resize(img, dim, interpolation=cv2.INTER_AREA)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`
By the way, are there any requirements for the resolution, format and size of the H&E images? Can  this image be the same as tissue_hires_image in the spatial file？
Thank you so much for your help!

**Comment by ktpolanski** [comment]
As per the demo notebook, please use the high resolution morphology image that was used for spaceranger, specifically the one that was passed via `--image`. This is the image on which the spatial coordinates are based.
