### ISSUE TITLE
How can I go to downstream analysis ?

### ISSUE THREAD

**Issue by ryupath** [Teichlab/bin2cell#21]
I am deeply impressed by your work bin2cell.
I ran through demonstration notebook.
Count data integrated into single cells was not found. How can I use ‘cdata’ ?

**Comment by ktpolanski** [comment]
I'm unsure what you're asking. As stated in the demo notebook, if you explicitly need counts for downstream application, you can round `cdata.X` to get counts.

**Comment by ryupath** [comment]
Thank you very much !
I wonder I could see cell boundaries by napari. In order to do this, I tried to add cell boundaries data made by stardist "he.npz" to cdata. 
However, the shape of the sparse matrix is not the same as cdata.X, so there was an error.
Cell boundaries data are stored in 2 .npz files. I want a "joint" version of the .npz file. 
I look forward to your reply.

**Comment by ktpolanski** [comment]
The function is now distributed as `b2c.view_labels()` in 0.3.2.
