### ISSUE TITLE
How could we convert cdata into Seurat object? 

### ISSUE THREAD

**Issue by LinAU** [Teichlab/bin2cell#23]
Thank you very much for the wonderful tools!  

I am now working with Visium HD data and would like to use seurat for some of the analysis after cell segmentation. May I ask how you suggest to convert the cdata into a seurat object?  

Thank you in advance for your help!

KR,
Lin

**Comment by ktpolanski** [comment]
Please look into existing Scanpy to Seurat conversion tools, being mindful of the fact they probably don't support image data.

**Comment by bmateosa** [comment]
@LinAU did you manage to open the Bin2Cell data in R to work with Seurat? I'm trying to do the same but I'm losing the image in the process.
Thank you.

**Comment by bmateosa** [comment]
I just found this package that solved my problem:
https://github.com/cellgeni/schard

**Comment by LinAU** [comment]
@bmateosa  Thanks!  I will try this as well!

**Comment by kyralindley** [comment]
@LinAU & @bmateosa : Hi! were you able to upload the cropped histology image into a seurat object using schard? I've used this package to upload the cdata, but am getting errors when i try and upload the cropped histology image.

**Comment by ktpolanski** [comment]
You can probably just make use of the built in Spaceranger high resolution one when working at cell scale.

**Comment by kyralindley** [comment]
@ktpolanski Do you know how to upload that image? Even when cropping the high res image it still throws the same errors

**Comment by ktpolanski** [comment]
Use the high res image and the spatial coordinates without cropping.
