### ISSUE TITLE
Error uploading bin2cell Processed Data & Cropped Image

### ISSUE THREAD

**Issue by kyralindley** [Teichlab/bin2cell#33]
Hi! I’m currently working with the bin2cell processed data and am struggling to re-integrate the cropped histology image back into a Seurat object. The workflow has been running smoothly up until the point of adding the cropped histology image, and I’m encountering issues with projecting my segmented data back onto the correct cropped image instead of the default, non-cropped histology image.

**Workflow**
I used bin2cell to process Visium data and improve the 2um output.
I successfully loaded the Seurat object from the .h5ad file using the schard package.
The cropped histology image (tissue_lowres_image.png) and tissue positions file (tissue_positions_list.csv) are ready and properly formatted.
Issue:
The cropped histology image does not seem to integrate correctly into the Seurat object. The segmented data is currently being projected back onto the original, un-cropped histology image, rather than the cropped version I want to use.

**What I’ve Tried**
I’ve followed the instructions to load the image and spatial coordinates into the Seurat object, but the image is not being mapped correctly.
The Read10X_Image() function has not worked as expected, and the segmented data is still aligning with the wrong image.

**Help**
Can you suggest the best packages or methods to upload and align the cropped histology image with my bin2cell processed data in Seurat? What would be the best approach to ensure the segmented data is projected onto the cropped histology image instead of the original? If there is a better way to do this with python, I am also open to those suggestions!

Any guidance would be much appreciated!

**Comment by ktpolanski** [comment]
Also raised in #23 

Spaceranger output has each bin referred to in two coordinate systems - an array grid, relative to the start of the array grid, and spatial coordinates relative to the full resolution morphology image. While preparing for segmentation, bin2cell creates another render of the morphology image and a cropped set of spatial coordinates. Those are used internally for the rest of the workflow, but do not replace the Spaceranger output, rather are present alongside it.

As mentioned in the other issue, using the Spaceranger output (the `hires` image, and the uncropped spatial coordinates) should hopefully be fine if schard supports it. Which it seems it does.

If there are any issues, please liaise with schard or Seurat.
