### ISSUE TITLE
Error with b2c.scaled_he_image()

### ISSUE THREAD

**Issue by bradgigax** [Teichlab/bin2cell#35]
I am having the same problem as comment #29.  

```
File ~/.local/lib/python3.9/site-packages/bin2cell/bin2cell.py:705, in actual_vs_inferred_image_shape(adata, img, ratio_threshold)
    702 #do the two match, within some tolerance of rounding etc?
    703 #divide both ways just in case
    704 if np.min(np.hstack((actual_dim/inferred_dim, inferred_dim/actual_dim))) < ratio_threshold:
--> 705     raise ValueError("Morphology image dimension mismatch. Dimensions inferred from Spaceranger output: "+str(inferred_dim)+", actual image dimensions: "+str(actual_dim)+". Are you running with ``source_image_path`` set to the full resolution morphology image, as used for ``--image`` in Spaceranger?")

ValueError: Morphology image dimension mismatch. Dimensions inferred from Spaceranger output: [33606.99885915 26487.91626749], actual image dimensions: [31606 33607]. Are you running with ``source_image_path`` set to the full resolution morphology image, as used for ``--image`` in `Spaceranger?`
```

```
print(np.shape(adata.uns["spatial"]['BG_Y12369_High_Res']["images"]["hires"]))
print(np.min(adata.obsm["spatial"],axis=0))
print(np.max(adata.obsm["spatial"],axis=0))
```
(6000, 4729, 3)
[3612.86561995 4792.48615448]
[28445.11050502 29472.01037198]

```
img = b2c.load_image(source_image_path)
img.shape
```
(31606, 33607, 3)

Y12369.tif[0] TIFF 33607x31606 33607x31606+0+0 8-bit sRGB 280.818MiB 0.000u 0:00.007
Y12369.tif[1] TIFF 16803x15803 16803x15803+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[2] TIFF 8401x7901 8401x7901+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[3] TIFF 4200x3950 4200x3950+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[4] TIFF 2100x1975 2100x1975+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[5] TIFF 1050x987 1050x987+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[6] TIFF 525x493 525x493+0+0 8-bit sRGB 0.000u 0:00.001
Y12369.tif[7] TIFF 262x246 262x246+0+0 8-bit sRGB 0.000u 0:00.001

It does not look like the solution to my problem is the same as #29. I would appreciate any help you can provide!

**Comment by ktpolanski** [comment]
Thanks for doing the same diagnostics as that issue, it makes my life a lot easier. Hopefully the error is informative enough to get the point across - the shrunken image loaded as part of the Spaceranger output looks like it came from a different source image than the one you've got here. The actual dimensions are off, the ratios of the dimensions are off (you can check the reverse-engineered ones versus the `hires` ones to see the calculation is not messed up, feel free to dig up the size factor and double check). At this point pretty much all you can do is actually take a look at the images.

**Comment by bradgigax** [comment]
Sorry it took so long to follow up, I never got a notification of that you replied. The thing that doesn't make sense to me is that this is the exact same image I input for SpaceRanger. It is also weird that one of the dimensions matches but not the other. Perhaps it is because I annotated the barcodes so that only those overlapping with tissue were included in the SpaceRanger run? Otherwise I can try to rerun SpaceRanger and see if that solves it.

**Comment by ktpolanski** [comment]
I remain quite confident that this is not the image Spaceranger was ran on - you technically have a shared dimension of 33607 on reinspection, but from shape alone it seems like the image was rotated and had things cropped from it in the other dimension prior to going into Spaceranger. If that's something you did, don't do that, or ingest the modified version. If you genuinely fed that exact file to Spaceranger, contact 10X customer support.

**Comment by bradgigax** [comment]
You would be absolutely correct... I accidentally uploaded the binned_outputs and spatial folder for the practice data to the folder containing my data. Oops! Works fine now. Sorry for wasting your time!

**Comment by chiwwong** [comment]
Hello, I have a similar error. I am quite sure that I have used the same image for spaceranger. However, I was doing a TMA. Therefore, I unselected some bins that belong to a separate sample. Do you think this will cause the error?

**Comment by ktpolanski** [comment]
I'm not sure what you're trying to say. If you ran multiple samples/slices on the same slide and then processed it via spaceranger, you can still process that slide via bin2cell and just split up your data later.

**Comment by alipirani88** [comment]
Hi @ktpolanski 

Not sure if this is the same issue but I double checked all the suggestions you made above.

Here are the diagnostics and I am not sure how to diagnose this issue, I am still new to image processing and would appreciate your help understanding this error:

`print(np.shape(adata.uns["spatial"]['238688-HD01_915422-5-2']["images"]["hires"]))
print(np.min(adata.obsm["spatial"],axis=0))
print(np.max(adata.obsm["spatial"],axis=0))` 

(3853, 3251, 3)
[  6.5270218  541.68058443]
[3135.37268963 3675.27479893]

`img = b2c.load_image(source_image_path)
img.shape`

(43287, 36523, 3)

`import tifffile as tf

img = tf.imread(source_image_path, key=0)
img.shape`

(43287, 36523, 3)

`thr = 10

#define a mask to easily pull out this region of the object in the future
mask = ((adata.obs['array_row'] >= 3050) & 
        (adata.obs['array_row'] <= 3250) & 
        (adata.obs['array_col'] >= 2350) & 
        (adata.obs['array_col'] <= 2550))

bdata = adata[mask] # read a crop of the object 
b2c.scaled_he_image(bdata, mpp=mpp) # genertae a ref H&E only from th region of interest 
#sc.set_figure_params(figsize=[5,5],dpi=100)
#bdata = bdata[bdata.obs['n_counts_adjusted']>thr]
#sc.pl.spatial(bdata, color=[None, "n_counts_adjusted"],alpha=0.5,cmap='gist_rainbow',img_key="0.5_mpp", basis="spatial_cropped")


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[36], line 10
      4 mask = ((adata.obs['array_row'] >= 3050) & 
      5         (adata.obs['array_row'] <= 3250) & 
      6         (adata.obs['array_col'] >= 2350) & 
      7         (adata.obs['array_col'] <= 2550))
      9 bdata = adata[mask] # read a crop of the object 
---> 10 b2c.scaled_he_image(bdata, mpp=mpp) # genertae a ref H&E only from th region of interest 
     11 #sc.set_figure_params(figsize=[5,5],dpi=100)
     12 #bdata = bdata[bdata.obs['n_counts_adjusted']>thr]
     13 #sc.pl.spatial(bdata, color=[None, "n_counts_adjusted"],alpha=0.5,cmap='gist_rainbow',img_key="0.5_mpp", basis="spatial_cropped")

File /rsrch5/home/neuro_rsrch/apirani/bin2cell_env/lib/python3.10/site-packages/bin2cell/bin2cell.py:1152, in scaled_he_image(adata, mpp, crop, buffer, spatial_cropped_key, store, img_key, save_path)
   1149 img = load_image(adata.uns['spatial'][library]['metadata']['source_image_path'])
   1150 #assess that the image dimensions match what they're supposed to be
   1151 #if not, inform the user what image they should retrieve and use
-> 1152 actual_vs_inferred_image_shape(adata, img)
   1153 #crop image if necessary
   1154 if crop:

File /rsrch5/home/neuro_rsrch/apirani/bin2cell_env/lib/python3.10/site-packages/bin2cell/bin2cell.py:1006, in actual_vs_inferred_image_shape(adata, img, ratio_threshold)
   1003 #do the two match, within some tolerance of rounding etc?
   1004 #divide both ways just in case
   1005 if np.min(np.hstack((actual_dim/inferred_dim, inferred_dim/actual_dim))) < ratio_threshold:
-> 1006     raise ValueError("Morphology image dimension mismatch. Dimensions inferred from Spaceranger output: "+str(inferred_dim)+", actual image dimensions: "+str(actual_dim)+". Are you running with ``source_image_path`` set to the full resolution morphology image, as used for ``--image`` in Spaceranger?")

ValueError: Morphology image dimension mismatch. Dimensions inferred from Spaceranger output: [3853. 3251.], actual image dimensions: [43287 36523]. Are you running with ``source_image_path`` set to the full resolution morphology image, as used for ``--image`` in Spaceranger?
`

I checked the image alignment and doesnt seem to be rotated and is similar to the spaceranger output. Also the bigtiff image size is 4.81 Gb
