### ISSUE TITLE
Combine multiple bin2cell output objects into one

### ISSUE THREAD

**Issue by sudarshan227** [Teichlab/bin2cell#38]
Hello all, I've been trying to combine multiple bin2cell output objects into one object file to better correct for batch effects with downstream analysis. However, I have been running into issues getting all of the metadata to carry over along with not being sure how to handle non-unique variables across the samples. Tried multiple approaches with anndata.concat such as this one: combined_adata = ad.concat([adata1, adata2, adata3], axis=0, join='outer', merge="same", label='sample', keys=['sample1', 'sample2', 'sample3']). Wondering if anyone has a way to ensure that all data (i.e. obs, var, uns) from all samples are adequately kept in the combined object.

**Comment by sudarshan227** [comment]
Thank you for the detailed answer. With the following code I am getting very close to the desired result:

`
adata.obs["sample"] = sample
adata.obs_names = [sample+"_"+i for i in adata.obs_names]
adata_combined = ad.concat([adata1, adata2, ...], join="outer", merge="same", uns_merge="unique", index_unique=None)
`
However, the one issue I am running into is with the var axis. I am losing all information in var because of the n_cells column (number of segmented cell objects from bin2cell that express gene of interest). Is there a reason I should keep this column after the qc step sc.pp.filter_genes(adata, min_cells=3)?

**Comment by ktpolanski** [comment]
Yeah that column is not that relevant. As long as you have gene names (and ideally ENSG gene IDs) you'll be ok.

**Comment by sudarshan227** [comment]
Great, thank you for your help!
