### ISSUE TITLE
Quality of H&E Staining Impacting Bin2Cell Output

### ISSUE THREAD

**Issue by bradgigax** [Teichlab/bin2cell#39]
Hello, I was running bin2cell on two different runs of HD Visium that I have. I noticed that there is a significant difference between these two runs in the quality of the H&E staining. I copied and pasted two examples below. The nuclei staining is much poorer in one of these images, which significantly impacts the ability of StarDist to identify cells. I am not sure if there is a work around for this or if anyone else faced this issue?

Slide 1 (Poor Quality; many undetected nuclei)
![image](https://github.com/user-attachments/assets/1bfc66db-7856-4899-8c23-36c46914475e)
Slide 2 (High Quality)
![image](https://github.com/user-attachments/assets/f6f86e97-4976-42b7-a07f-846152026639)

**Comment by nadavyayon** [comment]
hi, i'm not quite sure if you are asking about bin2cell or about segmenting challenging imaging data? personally, from an experimental perspective i think the hematoxylin stain was insufficient in the top image.

**Comment by ktpolanski** [comment]
Think Nadav has you covered here, kind of hard to pin this one on bin2cell, there's only so much you can do with low quality data. You could try lowering the Stardist stringency further. You could try mucking about with the image and try to tease out the nuclei a bit better with some contrast. Hopefully some of the areas where the morphology fails will get picked up by the GEX labels.

**Comment by bradgigax** [comment]
Thank you both for both of your replies. I did not want to insinuate this was a problem with bin2cell per se, but I was wondering if anyone else had faced this issue.

I also thought about messing around with the image using some filtering and contrast, but my worry is that anything I do will bias the results from this set of images compared to the other. I am not sure if there is a way to normalize them to make things more even between them.
