### ISSUE TITLE
Error when using `b2c.scaled_he_image`

### ISSUE THREAD

**Issue by lijxug** [Teichlab/bin2cell#6]
Hi team, 
I've encountered an error when running the line:
`b2c.scaled_he_image(adata, mpp=0.3, save_path="stardist/he.tiff")`. 
The error log is shown here: 
```
    695 #need to reverse dimension order and turn to int for cv2
    696 dim = (np.array(img.shape[:2])*scalef).astype(int)[::-1]
--> 697 img = cv2.resize(img, dim, interpolation=cv2.INTER_AREA)
    698 #we have everything we need. store in object
    699 adata.uns['spatial'][library]['images'][str(mpp)+"_mpp"] = img

error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

I am guessing that may be due to the giant size of my fullres image cuz one of my sample got passed. Any idea how to solve this or to work around it?

**Comment by nadavyayon** [comment]
Hi, can we have some details on the image? Size? Channels? Perhaps the order of the Channels in the array? (czy, xyc... etc) 

Thanks 

N

**Comment by ktpolanski** [comment]
I've seen the error twice before, once #5 and once locally, and in both cases this was the case of trying to run the function on the CytAssist image rather than the morphology one. Be sure to run it on the morphology one. If you've got an IF image, then use the IF image loader rather than the H&E one.

If your image is definitely an H&E morphology one and this is happening, then please provide more detail.

**Comment by ktpolanski** [comment]
Alright, I just went spelunking, replicating the local case as I remember what inputs the guy used. TL;DR I'm quite confident you're not actually using the full scale morphology image, the one matching the spatial coordinates.

The error was encountered locally when using the 10X demo lung IF data, and accidentally pointing to the CytAssist image. The crop coordinates generated with the default 150 buffer are `(520, 4296, 21521, 25213)`. Meanwhile the CytAssist image is 3000 by 3200, so you subset it with the crop and get an empty image. And OpenCV understandably complains.

It's good to have a bit more understanding into why this is happening.

**Comment by lijxug** [comment]
Thanks for the quick response and the explanation!
I've checked the sample a few times now, and I'm still scratching my head. I don't see anything obviously wrong. 
The image is right, and the hires image seems perfectly aligned.
I then run the function with the argument `crop = False`. However, there's a new error occured in following steps. 

Following a success run of `b2c.stardist(image_path="stardist/he.tiff", labels_npz_path="stardist/he.npz", stardist_model="2D_versatile_he",  prob_thresh=0.1)`, `b2c.insert_labels(adata, labels_npz_path="stardist/he.npz", basis="spatial", spatial_key="spatial_cropped",mpp=mpp, labels_key="labels_he")` yielded this: 

```
bin2cell.py (598): invalid value encountered in cast
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'csr_matrix'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/internals/blocks.py:1429, in Block.setitem(self, indexer, value, using_cow)
   1428 try:
-> 1429     values[indexer] = casted
   1430 except (TypeError, ValueError) as err:

ValueError: setting an array element with a sequence.

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[212], line 1
----> 1 b2c.insert_labels(adata, 
      2                   labels_npz_path="stardist/he.npz", 
      3                   basis="spatial", 
      4                   spatial_key="spatial_cropped",
      5                   mpp=mpp, 
      6                   labels_key="labels_he"
      7                  )

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/bin2cell/bin2cell.py:826, in insert_labels(adata, labels_npz_path, basis, spatial_key, mpp, labels_key)
    819 mask = ((coords[:,0] >= 0) & 
    820         (coords[:,0] < labels_sparse.shape[0]) & 
    821         (coords[:,1] >= 0) & 
    822         (coords[:,1] < labels_sparse.shape[1])
    823        )
    824 #pull out the cell labels for the coordinates, can just index the sparse matrix with them
    825 #insert into bin object, need to turn it into a 1d numpy array from a 1d numpy matrix first
--> 826 adata.obs.loc[mask, labels_key] = np.asarray(labels_sparse[coords[mask,0], coords[mask,1]]).flatten()

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/indexing.py:911, in _LocationIndexer.__setitem__(self, key, value)
    908 self._has_valid_setitem_indexer(key)
    910 iloc = self if self.name == "iloc" else self.obj.iloc
--> 911 iloc._setitem_with_indexer(indexer, value, self.name)

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/indexing.py:1942, in _iLocIndexer._setitem_with_indexer(self, indexer, value, name)
   1939 # align and set the values
   1940 if take_split_path:
   1941     # We have to operate column-wise
-> 1942     self._setitem_with_indexer_split_path(indexer, value, name)
   1943 else:
   1944     self._setitem_single_block(indexer, value, name)

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/indexing.py:2016, in _iLocIndexer._setitem_with_indexer_split_path(self, indexer, value, name)
   2013 elif len(ilocs) == len(value):
   2014     # We are setting multiple columns in a single row.
   2015     for loc, v in zip(ilocs, value):
-> 2016         self._setitem_single_column(loc, v, pi)
   2018 elif len(ilocs) == 1 and com.is_null_slice(pi) and len(self.obj) == 0:
   2019     # This is a setitem-with-expansion, see
   2020     #  test_loc_setitem_empty_append_expands_rows_mixed_dtype
   2021     # e.g. df = DataFrame(columns=["x", "y"])
   2022     #  df["x"] = df["x"].astype(np.int64)
   2023     #  df.loc[:, "x"] = [1, 2, 3]
   2024     self._setitem_single_column(ilocs[0], value, pi)

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/indexing.py:2175, in _iLocIndexer._setitem_single_column(self, loc, value, plane_indexer)
   2165     if dtype == np.void:
   2166         # This means we're expanding, with multiple columns, e.g.
   2167         #     df = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})
   (...)
   2170         # Here, we replace those temporary `np.void` columns with
   2171         # columns of the appropriate dtype, based on `value`.
   2172         self.obj.iloc[:, loc] = construct_1d_array_from_inferred_fill_value(
   2173             value, len(self.obj)
   2174         )
-> 2175     self.obj._mgr.column_setitem(loc, plane_indexer, value)
   2177 self.obj._clear_item_cache()

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/internals/managers.py:1337, in BlockManager.column_setitem(self, loc, idx, value, inplace_only)
   1335     col_mgr.setitem_inplace(idx, value)
   1336 else:
-> 1337     new_mgr = col_mgr.setitem((idx,), value)
   1338     self.iset(loc, new_mgr._block.values, inplace=True)
   1340 if needs_to_warn:

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/internals/managers.py:415, in BaseBlockManager.setitem(self, indexer, value, warn)
    411     # No need to split if we either set all columns or on a single block
    412     # manager
    413     self = self.copy()
--> 415 return self.apply("setitem", indexer=indexer, value=value)

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/internals/managers.py:363, in BaseBlockManager.apply(self, f, align_keys, **kwargs)
    361         applied = b.apply(f, **kwargs)
    362     else:
--> 363         applied = getattr(b, f)(**kwargs)
    364     result_blocks = extend_blocks(applied, result_blocks)
    366 out = type(self).from_blocks(result_blocks, self.axes)

File ~/mambaforge/envs/SpatialRNA/lib/python3.11/site-packages/pandas/core/internals/blocks.py:1432, in Block.setitem(self, indexer, value, using_cow)
   1430     except (TypeError, ValueError) as err:
   1431         if is_list_like(casted):
-> 1432             raise ValueError(
   1433                 "setting an array element with a sequence."
   1434             ) from err
   1435         raise
   1436 return self

ValueError: setting an array element with a sequence.
```

BTW, is there any other way to quickly visualize the whole slide? `sc.pl.spatial` is too slow for the job.

**Comment by ktpolanski** [comment]
Let's do some actual diagnostics - load the image the way b2c does and see what we've got to work with. Please provide me with the actual image name you're using here. You're looking for the very image that was provided as `--image` to spaceranger when mapping.

```python3
img = b2c.load_image("/path/to/full/morphology/image.tiff")
img.shape
np.min(adata.obsm["spatial"],axis=0)
np.max(adata.obsm["spatial"],axis=0)
```

As for visualisation, the AnnData object has the images stored as numpy arrays internally, and `plt.imshow()` can be used to show them.

```python3
#identify name of spatial key for subsequent access of fields
library = list(adata.uns['spatial'].keys())[0]
plt.imshow(adata.uns["spatial"][library]["images"]["0.3_mpp"])
```

I'm still quite convinced there's a size mismatch going on, as if there was something funky with the cv2 loading the TIFF you'd think the errors would kick in earlier. That failing, if there is something funky with the cv2 loading, we can try to circumvent that somehow.

**Comment by lijxug** [comment]
Sure, I've run `b2c` on my own dataset, and have to hide my sample name.
By running this 
```
source_image_path
img = b2c.load_image(source_image_path)
img.shape
np.min(adata.obsm["spatial"],axis=0)
np.max(adata.obsm["spatial"],axis=0)
```
I've got 
```
'/PathToMyProject/MyHDSampleID-20X.tif'
(18989, 20000, 3)
array([nan, nan])
array([nan, nan])
```

**Comment by ktpolanski** [comment]
Huh, now that's something I haven't seen before - it seems the spatial coordinates are shot rather than the image. Are they fully or partially shot? More diagnostics!

```python3
adata.shape
np.sum(np.isnan(adata.obsm["spatial"]), axis=0)

**Comment by lijxug** [comment]
Sure. The output is 
```
(10729616, 18085)
array([1, 1])
```
Noted that this comes from an unfiltered adata.

I also pinpoint the `nan` spot in the `spatial` slot with `np.argwhere(np.isnan(adata.obsm["spatial"]))`
```
array([[2571605,       0],
       [2571605,       1]])
``` 
I wonder if removing it could help

**Comment by lijxug** [comment]
Well, no, the `array_row` and `array_col` of that spot are both `nan`
```
in_tissue   NaN
array_row   NaN
array_col   NaN
Name: s_002um_00000_00000-1, dtype: float64
```

**Comment by ktpolanski** [comment]
Interesting, I loaded up a local positions parquet to investigate and it seems you may somehow be missing the very first one. At least on my end `s_002um_00000_00000-1` is the very first index in the loaded file. Assuming `path` pointing to the 2um bin output like in the tutorial, try this:
```python3
positions = pd.read_parquet(path+"spatial/tissue_positions.parquet")
```
On my end `positions` has 11222500 rows (3350x3350, as expected) and a clear header, including `barcode` which is shortly thereafter set as the index. How's it looking on your end?

**Comment by ktpolanski** [comment]
Well, at least you can technically port in the missing data for the spot if you so choose?

The only processing that is done after loading is `positions.set_index("barcode", inplace=True)`. Guess you could try that in case that somehow messes it up, but I don't expect it would.

This is very strange. The two data frames (`adata.obs` and `positions` with the index set) are joined via existing `sc.read_visium()` syntax of `adata.obs = adata.obs.join(positions, how="left")`. It doesn't seem to be hiccupping away any entries on my end, nor was this reported before by other users.

Ideally I'd like to get my paws on your 2um binned output folder to see if I can replicate this on my end, but understand this may not be possible.

**Comment by ktpolanski** [comment]
Alright, I think I've figured out a simple test of the relevant part of the logic:
```python3
#or use raw if you specified count_file = "raw_feature_bc_matrix.h5" in b2c.read_visium()
bdata = sc.read_10x_h5(path+"filtered_feature_bc_matrix.h5")
positions = pd.read_parquet(path+"spatial/tissue_positions.parquet")
positions.set_index("barcode", inplace=True)
joined = bdata.obs.join(positions, how="left")
np.sum(np.isnan(joined), axis=0)
```

As for sharing, the data can be easily removed by either blanking the count matrix
```python3
bdata.X.data = np.zeros(bdata.X.data.shape)
bdata.X.eliminate_zeros()
bdata.write("empty-object.h5ad")
```
or writing out the dummy "obs" after loading the data
```python3
bdata.obs.to_csv("obs.csv")
```
Either of those in combination with `tissue_positions.parquet` should allow me to try something at least.

**Comment by lijxug** [comment]
The result does not harbor any `nan`, well, this is as expected I guess.
```
in_tissue             0
array_row             0
array_col             0
pxl_row_in_fullres    0
pxl_col_in_fullres    0
dtype: int64
```
As for sharing the demo, the zipped file is about 220 MB and maybe it's more easier for me to send you by email instead of directly posting online.

**Comment by ktpolanski** [comment]
This is not fully expected - It seems to imply stuff is working as intended and there's no hiccup, whereas this same exact logic within the loader somehow hiccups.

Just in case, try restarting things and run the loader again and see if it magically fixes itself?

**Comment by lijxug** [comment]
I was running b2c on a jupyter kernel. As the matter of fact, the kernel has been restarted several times during my tests and this bug remains. Unfortunately, the new way to handle the path did not produce `nan` either.

Anyway, for me I guess this problem has been solved somehow, although I'll have to manually replace the `nan`s.  
If you want to delve into details, I'd be happy to send you the dummy data through the email.

**Comment by ktpolanski** [comment]
Seems there's something very ephemeral going on here. Given the fact the dummy example does not produce `nan`s on your end, think pretty much the only thing that would make sense to share would be the full 2um binned output folder, though you can instead ensure there's no tissue images there (I can slot in some dummy replacement local ones for the sake of the code progressing).

One last stupid improbable test - have you tried running the b2c loader after the focused parquet testing, in the same kernel?

**Comment by lijxug** [comment]
Hey! I've located the problem!
I've went through the code of the b2c loader and noticed that it choose to load "tissue_positions.csv" first if there's one. Unfortunately, my "tissue_positions.csv" is home-made to cope another tool. Although I still dont understand why it works for other samples, removing the malfunctioning one does fix the problem. Thanks for debugging with me and I'm sorry for your trouble! 
Closing the issue now

**Comment by ktpolanski** [comment]
Thanks for coming back with info. This was still an interesting excursion into what would happen were nans to appear in the object somehow.

I think I can explain what happened with that exact sample for you. If you check the scanpy loader logic for `tissue_positions.csv`, you'll find the following:
```python3
positions = pd.read_csv(
    files["tissue_positions_file"],
    header=0 if tissue_positions_file.name == "tissue_positions.csv" else None,
    index_col=0,
)
```
`tissue_positions.csv` is actually the second iteration of 10X's files, the first one was `tissue_posititons_list.csv` and it was headerless. Somewhere down the line, they introduced the revolutionary concept of a header, and the code respects that. My best guess is that your file is actually headerless, but named like the headered version, which gets the first row eaten as a "header" that gets promptly overridden by column names. In the snippet you shared above, your first row was `in_tissue`. I can imagine the 0,0 coordinate in the array grid is absent from the tissue more often than not.
