### ISSUE TITLE
What would be the recommended file format of input H&E image?

### ISSUE THREAD

**Issue by chiwwong** [Teichlab/bin2cell#7]
Thank you for making such a wonderful tool. I have a question that might not be directly related to your project but I encountered some problems with the one mentioned in 10X [blog](https://www.10xgenomics.com/analysis-guides/segmentation-visium-hd) when performing image segmentation with my own image. 

Long story short, my image scanner generates svs files (for some reason, I cannot get btf out from there). I know there are a couple of converters, such as [bftools](https://bio-formats.readthedocs.io/en/stable/users/index.html). However, I would like to know what would be the format of the input files (e.g. the channel order etc). 

I am new to coding and python, I would greatly appreciate it if you could also give me some hits on getting the input files ready (given my unsuccessful conversion of images using bftools). 

The README file mentioned bin2cell segmentation can be done on the H&E image and/or a visualization of the gene expression, but the demo workbooks only showcased the use of the combination of them. Would you mind pointing me in the direction of how to get finer control of the segmentation for the H&E? I would like to first test out two staining protocols to see which one will get better segmentation without the gene expression profile. Do you think staining that boosts the nuclear stain would result in a better segmentation output? Or do you think that is an overkill? (I understand, this might be a question related to `StarDist` instead, but would like to get your advice on whether with a combination of the gene expression segmentation, the importance of H&E nucleus detection is not as crucial as before.)

**Comment by nadavyayon** [comment]
Hi, 

Indeed this is more relevant to stardist.  The best way to try out different parameters is to use Fiji where you can also open most image formats and save as tiff. This will allow you to also visualize the output.  The same parameters can then be used for bin2cell. I would crop your image to a test region as Fiji would struggle to do the whole thing.  You also need to play with the image resolution (we call it mpp) to get the best performance from stardist.  

Hope this helps and generally speaking there is a fantastic image analysis forum 
https://forum.image.sc/ which I would highly recommend for anything that has to do with image analysis.  

Best of luck 

N

**Comment by chiwwong** [comment]
Thank you for your prompt reply. You mentioned cropping the image for import and export in imagej. I wonder whether that will complicate the `b2c.scaled_he_image()`? The demo mentioned the function will crop the image and align it to the region that had actual Visium HD performed. This is a more theoretical question: would it work if the supplied image does not fully cover the actual Visium HD capture area? (I am apoligize I do not have data to test it out).

Though theoretical, this could be a valid question as I am doing Visium HD on tissue array. Do you have any advice on whether I should cut each tissue core out and perform the segmentation individually given the cell/ nucleus size is heterogeneous among the tissue cores within a tissue array?

**Comment by nadavyayon** [comment]
Hi, 

You mentioned that you want to play with different parameters for segmentation, so I suggested to do it with fiji for ease and interactivity and since it has a simple and fast plug-in for stardist with the same models we use.

This has nothing to do with bin2cell. You would still run bin2cell normally with the original image (converted to a format that is supported) not cropped in anyway. You would then use the same parameters and image resolution that you came up with in your

**Comment by ktpolanski** [comment]
Bin2cell specifically expects TIFF files, as you noticed. As for the TIFF contents, I think it just expects a straight up RGB (as per ImageMagick):

```
$ identify Visium_HD_Mouse_Brain_tissue_image.tif
Visium_HD_Mouse_Brain_tissue_image.tif TIFF 18872x23947 18872x23947+0+0 8-bit sRGB 137.865MiB 0.000u 0:00.033
```

The 10X demo IF image is multichannel, and there's a bespoke loader for that, but I don't think you need that for the H&E.

**Comment by ktpolanski** [comment]
I haven't worked with SVS files myself, but it seems that [OpenSlide](https://openslide.org/api/python/) is a library capable of handling the format. [This post](https://medium.com/@digitalboi-saurabh/how-to-convert-svs-to-jpeg-with-python-using-tifffile-d2523f9af100) has some syntax for pulling in the SVS contents, turning them Pillow-compatible and then writing them out. Think that doing the saving as `.save("filename.tiff")` should probably do the trick without needing to specify formats.

Of note, the Python wrapper around OpenSlide requires the underlying C library, but that's [on Conda](https://anaconda.org/conda-forge/openslide) if you need it.

**Comment by ktpolanski** [comment]
Oh also I checked with Nadav and apparently "I would crop your image to a test region as Fiji would struggle to do the whole thing" specifically refers to testing out StarDist interactively. As per his expertise, Fiji should hopefully be able to handle the SVS -> TIFF conversion, so you have two things to try!
