### ISSUE TITLE
Per-label expansion not working

### ISSUE THREAD

**Issue by janinemelsen** [Teichlab/bin2cell#9]
Hi!

I am trying to apply a per-label expansion by setting the max_bin distance at None.

`b2c.expand_labels(adata, 
                  labels_key='labels_he001nms03', 
                  expanded_labels_key="labels_he_expanded",
                  max_bin_distance=None
                 )`

However I receive the following error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[42], line 1
----> 1 b2c.expand_labels(adata, 
      2                   labels_key='labels_he001nms03', 
      3                   expanded_labels_key="labels_he_expanded",
      4                   max_bin_distance=None
      5                  )

File /exports/immu-staallab/Janine/visiumhd_env/lib/python3.12/site-packages/bin2cell/bin2cell.py:780, in expand_labels(adata, labels_key, expanded_labels_key, max_bin_distance, subset_pca)
    778 calls = labels[hits]
    779 #first case - one bin is closer than the others
--> 780 clear_mask = ((dists[:,0]<dists[:,1]) & (dists[:,0]<=max_bin_distance))
    781 #get their indices in the original cell space
    782 clear_query_inds = full_query_inds[clear_mask]

TypeError: '<=' not supported between instances of 'float' and 'NoneType'`

Is there anything I can do to solve this problem?

**Comment by ktpolanski** [comment]
You're using an older version of bin2cell, update from pip, that should sort it out.

**Comment by janinemelsen** [comment]
Perfect, thanks!
